name: fx_helper
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/muhammadaufa07/fx_helper"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.5.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  local_auth: ^2.3.0
  local_auth_android: ^1.0.49
  local_auth_darwin: ^1.4.3
  fluttertoast: ^9.0.0
  syncfusion_flutter_core: ^31.1.19
  syncfusion_flutter_pdfviewer: ^31.1.19
  printing: ^5.14.2
  pdf: ^3.11.3
  http_parser: ^4.1.2
  file_picker: ^10.3.3
  month_picker_dialog: ^6.5.0
  calendar_date_picker2: ^2.0.1
  image_picker: ^1.2.0
  photo_view: ^0.15.0
  google_fonts: ^6.3.2
  package_info_plus: ^9.0.0
  logging: ^1.3.0  
  flutter_secure_storage: ^9.2.4
  awesome_snackbar_content: ^0.1.8
  flutter_html: ^3.0.0
  youtube_player_flutter: ^9.1.3
  html: ^0.15.6
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  mime: ^2.0.0
  open_file_manager: ^2.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter: 
  assets:
    # - assets/icons/
    - assets/images/
    # - assets/lotties/
    # - assets/backgrounds/
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
